/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.php',
    './includes/render/**/*.php',
    './admin/**/*.php',
    './assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#abcae5',
        'on-error-container': '#93000a',
        'surface-container-high': '#eae8e7',
        'on-tertiary-fixed': '#00201e',
        'surface-container-low': '#f5f3f3',
        'surface-dim': '#dbd9d9',
        'surface-container': '#f0eded',
        'secondary-container': '#c4e3ff',
        tertiary: '#002c2a',
        'surface-variant': '#e4e2e2',
        'tertiary-container': '#004441',
        'surface-container-highest': '#e4e2e2',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f2f0f0',
        background: '#fbf9f8',
        'inverse-surface': '#303030',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001a41',
        'on-surface': '#1b1c1c',
        'on-primary-container': '#8aa7e1',
        'on-tertiary-container': '#71b2ad',
        'tertiary-fixed': '#acefe9',
        'on-secondary-fixed': '#001e2f',
        secondary: '#446279',
        'on-tertiary-fixed-variant': '#00504c',
        'on-background': '#1b1c1c',
        'tertiary-fixed-dim': '#91d2cd',
        outline: '#747780',
        'on-surface-variant': '#43474f',
        'on-secondary-container': '#48667d',
        'primary-container': '#1b3b6f',
        'inverse-primary': '#acc7ff',
        'surface-tint': '#415e94',
        primary: '#002555',
        'primary-fixed': '#d8e2ff',
        error: '#ba1a1a',
        'primary-fixed-dim': '#acc7ff',
        'secondary-fixed': '#cae6ff',
        'on-secondary': '#ffffff',
        'outline-variant': '#c4c6d1',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#2b4a60',
        'surface-bright': '#fbf9f8',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#28467b',
        surface: '#fbf9f8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
